### ISSUE TITLE
Array or property instantiation without a default value

### ISSUE THREAD

**Issue by dannewnsjump24** [JumpTwentyFour/php-coding-standards#26]
https://github.com/Paramount-Business-Jets/charter-insight-laravel/pull/1447

this PR probably better explains the issue, but can we potentially create some kind of sniff or ecs rule that checks that if we're creating a property that its not accessed before instantiation

as shown by the sentry error here https://user-images.githubusercontent.com/67474738/225644280-941b9700-bb2a-4228-87fb-bcffc39dbf54.png

**Comment by mantebalzaraviciute** [comment]
I found a stan solution so included it in laravel standards repo :) 
https://github.com/JumpTwentyFour/laravel-coding-standards/pull/16
